version: '3.8'

services:
  backend:
    build:
      context: ./Src/BackEnd
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=/app/BackEnd/API/api.py
      - FLASK_ENV=production
      - PYTHONPATH=/app
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    networks:
      - mtg-network

  frontend:
    build:
      context: ./Src/FrontEnd
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - BACKEND_URL=http://backend:5000
    depends_on:
      backend:
        condition: service_healthy
    networks:
      - mtg-network

networks:
  mtg-network:
    driver: bridge
